Feature branch-mile_stone_1
luqmanmusah/thenextweek_clone pull request #2
Opened 2021-02-01 15:38 UTC by tta2yta

we created a branch called "Feature branch" for the development of the application.
On the initial commit, we created a basic structure for the page and added bootstrap links, CDN and Font awesome, as well as set up linter configured it.

In this section, we have done the Header, the footer section, and the three columns of the main section of thenextweek website.
The "Mobile first" approach is used in order to achieve responsiveness principles.
Elements are styled using bootstrap classes and custom CSS file
The issues raised from the first review of the project in the dashboard are fully addressed.

Please review my project before I merge my branch.
Thanks in advance!

2021-02-01 15:57 UTC, PhillipUg requested changes
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement before moving on to your next milestone 🔍

### Approved with Changes Required ♻️ 

- [x] First of all, fix all linter errors. Kindly ensure to fix all linter errors before submitting for review in all your future projects

#### Header
* [x] The main navigation (menu)
  - Uses a nav tag
  - It has a form with the search field

#### Please note that this request will be approved in the dashboard and you don’t need to submit it for re-review or merge this request into the main branch please make the suggested changes and move on to the next milestone. When you're done with the next milestone, submit this request again, don't create a new pull request. You are to keep submitting this same pull request until project completion.

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-02-02 15:11 UTC, luqmanmusah commented
We have completed the second milestone, we created the 3 columns main section of the website for the 3 screen sizes;
Column 1
Featured stories
Sponsored insights / Rankings

Column 2
Top story
My turn
Culture & travel
More stories
Latest news

Column 3
The debate
Opinion
Sponsored insights / Rankings
Free signup

We have also finished Milestone 3, we completed the last sections of the website. That is;

Create three sections of the website for the 3 screen sizes
Make sure you have a descriptive README.

Thank you.

2021-02-02 17:45 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @tta2yta and @luqmanmusah! 👋 
You are making such great progress on this project so far👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
### GENERAL
- [x] You are using a lot of css styling that can be done with bootstrap classes. Please take a look at this [cheat sheet](https://hackerthemes.com/bootstrap-cheatsheet/) and see what rules you can replace with bootstrap classes. 
- [x] Your linters are failing. Please fix the errors before moving on


- [x] There are borders around the subscribe and newsletter items and there shouldn't be. This issue persists on the tablet and mobile screens as well.
Your clone 👇🏾 
![Screen Shot 2021-02-02 at 6 12 21 PM](https://user-images.githubusercontent.com/48804258/106636414-325c5d80-6582-11eb-9b7d-38e9c50f6410.png)
The original page 👇🏾 
<img width="1362" alt="Screen Shot 2021-02-02 at 6 13 04 PM" src="https://user-images.githubusercontent.com/48804258/106636518-4c963b80-6582-11eb-8453-03e7c62aa295.png">
- [ ] There are borders around the articles in the In the Magazine and the Editors Picks sections and there shouldn't be. This issue persists on the tablet and mobile screens as well.
Your clone 👇🏾 

![Screen Shot 2021-02-02 at 6 16 14 PM](https://user-images.githubusercontent.com/48804258/106637256-bd3d5800-6582-11eb-91a8-ad1fda6c901b.png)

![Screen Shot 2021-02-02 at 6 16 29 PM](https://user-images.githubusercontent.com/48804258/106637283-c5959300-6582-11eb-8cd8-83b75db4e2be.png)

The original page 👇🏾 

<img width="1380" alt="Screen Shot 2021-02-02 at 6 17 30 PM" src="https://user-images.githubusercontent.com/48804258/106637393-eb229c80-6582-11eb-9eea-a66e6c0cf306.png">

<img width="1382" alt="Screen Shot 2021-02-02 at 6 17 42 PM" src="https://user-images.githubusercontent.com/48804258/106637410-f249aa80-6582-11eb-8db6-8b2a1755aed5.png">




### DESKTOP
- [x] Your search wraps to the next line on the bigger screen sizes
Your clone 👇🏾 
![Screen Shot 2021-02-02 at 6 08 48 PM](https://user-images.githubusercontent.com/48804258/106635939-b3672500-6581-11eb-81e3-3c30b901390e.png)
The original page 👇🏾 
<img width="1317" alt="Screen Shot 2021-02-02 at 6 09 08 PM" src="https://user-images.githubusercontent.com/48804258/106635986-bf52e700-6581-11eb-8b6d-fed7d42a9f1b.png">

### TABLET

- [ ] In the Main Newspaper sections (U.S., World, Business, Etc.) the 3 smaller images (in one column) remain the same size as the 2 bigger images which is causing it to spill off the page. 
Your clone 👇🏾 
![Screen Shot 2021-02-02 at 6 20 57 PM](https://user-images.githubusercontent.com/48804258/106637765-65ebb780-6583-11eb-8bb2-2748e16270fb.png)

The original page 👇🏾 
<img width="781" alt="Screen Shot 2021-02-02 at 6 21 14 PM" src="https://user-images.githubusercontent.com/48804258/106637801-700db600-6583-11eb-9397-45eea4ad0642.png">

- [ ] The space between the text and the magazine covers in the subscribe section needs to be reduced. 
Your clone 👇🏾 
![Screen Shot 2021-02-02 at 6 22 43 PM](https://user-images.githubusercontent.com/48804258/106637986-a51a0880-6583-11eb-8be4-41dacbd7d6b6.png)

The original page 👇🏾 
<img width="776" alt="Screen Shot 2021-02-02 at 6 23 06 PM" src="https://user-images.githubusercontent.com/48804258/106638040-b3682480-6583-11eb-8049-10b76f56e635.png">

- [ ] The image in the newsletter section should take the height of the entire box and the text should have less of a top padding.
Your clone 👇🏾 
![Screen Shot 2021-02-02 at 6 24 04 PM](https://user-images.githubusercontent.com/48804258/106638135-d561a700-6583-11eb-90c1-4ff6aaaa6d9b.png)

The original page 👇🏾 
<img width="743" alt="Screen Shot 2021-02-02 at 6 24 20 PM" src="https://user-images.githubusercontent.com/48804258/106638169-df83a580-6583-11eb-98dc-0a706a7cedfd.png">

### MOBILE

- [ ] In the Main Newspaper sections (U.S., World, Business, Etc.) the 3 smaller articles should be significantly smaller than they are at the moment. 
Your clone 👇🏾 

![Screen Shot 2021-02-02 at 6 28 05 PM](https://user-images.githubusercontent.com/48804258/106638653-65075580-6584-11eb-90e1-86ab3a4eb5b3.png)
![Screen Shot 2021-02-02 at 6 28 16 PM](https://user-images.githubusercontent.com/48804258/106638682-6b95cd00-6584-11eb-9da5-efef527e037d.png)

The original page 👇🏾 
![Screen Shot 2021-02-02 at 6 29 04 PM](https://user-images.githubusercontent.com/48804258/106638786-87996e80-6584-11eb-8879-3d42515bd65b.png)

![Screen Shot 2021-02-02 at 6 30 00 PM](https://user-images.githubusercontent.com/48804258/106638902-a992f100-6584-11eb-8948-3d48001e11a2.png)

- See my comments below for additional changes


****
### Please note that milestone 2 does not require a re-review and will be marked as approved in your dashboard, however these changes are MANDATORY. Please make the required changes before moving on to Milestone 3 🙏
Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    text-decoration: none;
- [ ] This can be done with the bootstrap class `text-decoration-none`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +  }
- [ ] This can be done with the bootstrap class `d-none`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +  }
- [ ] This can be done with the bootstrap class `w-100`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    max-width: 100%;
- [ ] This can be done with the bootstrap class `mw-100`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    text-align: center;
- [ ] This can be done with the bootstrap class `text-center`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    width: 50%;
- [ ] This can be done with the bootstrap class `w-50`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +  }
- [ ] This can be done with the bootstrap classes `mw-100` and `h-100`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    }
- [ ] This can be done with the bootstrap class `d-*-none` (`d-sm-none`/` d-md-none` /` d-lg-none`)

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    }
- [ ] Try not to use important unless it is absolutely necessary. This can be done with the bootstrap class `float-*-left` ( * => screen size)

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +      display: inline;
- [ ] This can be done with the bootstrap class `d-*-inline`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +      height: 100% !important;
- [ ] Try not to use `!important` if it can be avoided. This can be done with bootstrap classes.

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +      max-height: 100% !important;
- [ ] Try not to use `!important` if it can be avoided. This can be done with bootstrap classes.

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    text-align: center;
- [ ] This can be done with the bootstrap class `text-*-center`

2021-02-02 17:45 UTC, BrittanyBlake commented on css/style.css
> +    text-align: center;
- [ ] This can be done with bootstrap classes

2021-02-03 10:37 UTC, tta2yta commented
Hello. we have completed all three milestones for this project and we have also corrected the code reviews you mention in every milestone. So could you please make a code review for our project? Thank you for your time.

2021-02-03 19:32 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Luqman Musah & Tedros Andemichael** 
Good job with your first submission for this project :muscle:  :muscle:
Your page meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] In the "magazine" and "editor's pick" sections, some links to the images are broken

![](https://i.ibb.co/FnSYHLt/review43.png)

- [ ] In the "magazine" and "editor's pick" sections, every title should use a hx tag and have a link

| Yours | Original |
|:---:|:---:|
|![image](https://i.ibb.co/Sr1xTdx/review44.png) | ![image](https://i.ibb.co/VYNkqd0/review45.png) |

- [ ] Color of subscribe button, in the navbar, should be black
- [ ] Social links in the footer should have white background color
- [ ] In the style.css file, don't overuse important
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-03 22:59 UTC, tta2yta commented
Hello. we have corrected the points you mentioned. So, could you please make a code review for our project? Thank you for your time.

2021-02-04 11:57 UTC, uryelah approved these changes
Hi **Luqman Musah & Tedros Andemichael **, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job implementing most of the requests for this project!

You did a great job working out the responsiveness of the project!

Good luck with the next milestone! 🚀  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---

### **Optional Suggestions**

- [ ] Some of the images of thew "Opinion" section are still broken, please be more careful and check them thoroughly. 

- [ ] The background color of the site is not correct, you used a grey-ish pink instead of a pure shade of grey.
- A very easy way to make a grey color in hex or rgb is to simply repeat the same value three times:
Ex:
```
// Grey
#eeeeee
#b2b2b2
#d0d0d0
rgb(50,50,50)

// Not Grey
#e4eeee
#b1b2b3
#d0a1f2
rgb(55,50,45)
```

You may also simply use a color picker, eye-drop, tool form your browser dev tools or inspect the element you want to get the color code from and copy it.
You should NEVER try to guess a color when working as a web developer.

---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-02-04 12:24 UTC, merged